### ISSUE TITLE
output_audio.wav: No such file or directory

### ISSUE THREAD

**Issue by TouchstoneTheDev** [pranauv1/AI-Video-Translation#1]
![image](https://github.com/pranauv1/AI-Video-Translation/assets/101004444/562a47d0-072d-4728-9aae-7a7248950e6c)

**Comment by pranauv1** [comment]
It seems that your `video_path` variable is pointing to a file path which does not exist.
Try `print(video_path)` and check if that file exists, if not update the variable with the existing file path.

OR

`ffmpeg -i {video_path} -acodec pcm_s24le -ar 48000 -q:a 0 -map a -y 'output_audio.wav'` run this in a new cell and check the output.
